name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        platforms: linux/amd64,linux/arm64
    - name: Build the Docker image
      run: docker build -t tfnielson/duplo_tfnpy .
    - name: Push Docker Image
      run: docker push tfnielson/duplo_tfnpy .